### ISSUE TITLE
Trigger AD if proximity sensor is uncovered

### ISSUE THREAD

**Issue by tenghc** [gavinhungry/Xposed-AmbientNotifications#1]
Can it light up the display in ambient mode if the proximity is uncovered within 6 seconds?

**Comment by tenghc** [comment]
This is my suggested workflow of the ambient notification.

Step 1: Notifications come.
Step 2: Detect proximity sensor if it is covered or not for 6 seconds. (If covered for 6 seconds, jump to Step 4)
Step 3: If proximity sensor uncovered within 6 seconds, ambient notification lights up for 6 seconds.
Step 5: All sensor disabled including proximity sensor. Only "Notification Listener" is active.
Step 4: End.

P/S: May I ask? Is all AD sensor disabled during standby? It concerns me because it drains battery. All I need is just a "wake on notifications". Thanks Gavin! You are doing a great job there.

**Comment by gavinhungry** [comment]
It sounds like what you want is "Don't turn on the screen for ambient display if the proximity sensor is covered"?

**Comment by DeadneM** [comment]
Yes i think it's what he want, like in GravityBox

**Comment by tenghc** [comment]
Yes. That's it. I don't want it to trigger while in my pocket, but for a duration when you take the phone out it will activate AD.

**Comment by gavinhungry** [comment]
The first part of that is probably doable (don't activate Ambient Display when proximity sensor is covered), but the second part (activate Ambient Display when uncovering the proximity sensor) is outside of the scope of this module.

**Comment by tenghc** [comment]
Ok. Thanks for the clarification. Thank you sir!
