### ISSUE TITLE
Add dates

### ISSUE THREAD

**Issue by Shtiff** [gavinhungry/Xposed-AmbientNotifications#2]
Would it be possible to add a date to the ambient display, instead of just having time?

**Comment by gavinhungry** [comment]
I'm running CyanogenMod 13 (Marshmallow), so I don't know if this is a CM thing or an Android M thing, but I already have the date displayed as part of Ambient Display (along with the time).

**Comment by Shtiff** [comment]
Ya it's a CyanogenMod thing. Thank you.

**Comment by gavinhungry** [comment]
@Shtiff are you sure? Here's a video from a Nexus 6P review (running stock Android M, no doubt - not CyanogenMod), and you can clearly see the date visible in Ambient Display (starts at 03:02):
https://www.youtube.com/watch?v=UcEwASovpZE&t=3m2s

I don't really want to spend time implementing AOSP features for other versions of Android. :)

**Comment by Shtiff** [comment]
Ya I see. Maybe marshmallow??? I just run regular stock rom, haven't been that into flashing roms. XT1254, 5.1, SU4TL-44, rooted . no problem i was just trying to see if I could find it somewhere nothing that important. But if you get some free time, lol. Thank you for the response!

**Comment by gavinhungry** [comment]
Even on the Nexus 6 (back when it was running Lollipop), the date was displayed as part of Ambient Display:
https://www.youtube.com/watch?v=5TyhaOjME5g

So, I'm guessing you're running Motorola's implementation of Ambient Display. Closing for now (since I own no Motorola devices).
